services:

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: n8n_feedback_backend
    environment:
      DATABASE_URL: sqlite:///app/n8n_feedback.db
      FRONTEND_URL: http://104.131.8.230:3000
      CORS_ORIGINS: "http://localhost:3000,http://104.131.8.230:3000,http://127.0.0.1:3000,http://0.0.0.0:3000"
      PYTHONPATH: "/app"
      PYTHONUNBUFFERED: "1"
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - n8n_network
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 128M
    # Command is now handled by startup.sh script
    restart: always

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: n8n_feedback_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - n8n_network
    environment:
      - REACT_APP_API_URL=http://104.131.8.230:8000
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    command: npm start -- --max-old-space-size=256
    restart: always

# No volumes needed for SQLite

networks:
  n8n_network:
    driver: bridge
