services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: n8n_feedback_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: n8n_feedback
      MYSQL_USER: n8n_user
      MYSQL_PASSWORD: n8n_password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - n8n_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "n8n_user", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: n8n_feedback_backend
    environment:
      DATABASE_URL: mysql+pymysql://n8n_user:n8n_password@mysql:3306/n8n_feedback
    ports:
      - "104.131.8.230:8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - n8n_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: n8n_feedback_frontend
    ports:
      - "104.131.8.230:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - n8n_network
    environment:
      - REACT_APP_API_URL=http://104.131.8.230:8000

volumes:
  mysql_data:

networks:
  n8n_network:
    driver: bridge 