services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: n8n_feedback_db
    environment:
      POSTGRES_DB: n8n_feedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: n8n_feedback_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/n8n_feedback
    ports:
      - "104.131.8.230:8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - n8n_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: n8n_feedback_frontend
    ports:
      - "104.131.8.230:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - n8n_network
    environment:
      - REACT_APP_API_URL=http://104.131.8.230:8000

volumes:
  postgres_data:

networks:
  n8n_network:
    driver: bridge 